### ISSUE TITLE
calibration error 

### ISSUE THREAD

**Issue by c1p81** [GSNCodes/ArUCo-Markers-Pose-Estimation-Generation-Python#2]
trying to calibrate my camera i have this message
Traceback (most recent call last):
  File "/home/luca/Downloads/ArUCo-Markers-Pose-Estimation-Generation-Python-main/calibration.py", line 79, in <module>
    ret, mtx, dist, rvecs, tvecs = calibrate(dirpath, square_size, visualize=visualize, width=width, height=height)
  File "/home/luca/Downloads/ArUCo-Markers-Pose-Estimation-Generation-Python-main/calibration.py", line 52, in calibrate
    ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
cv2.error: OpenCV(4.5.1) ../modules/calib3d/src/calibration.cpp:3694: error: (-215:Assertion failed) nimages > 0 in function 'calibrateCameraRO'

i have  10 images in subfolder pose and i use this command
python3 calibration.py --dir pose/ --square_size 0.049

thanks
L

**Comment by c1p81** [comment]
found the solution ... the checkboard image was not correct
thanks

**Comment by GSNCodes** [comment]
@c1p81  Glad you were able to resolve it :)
All the best with your project.

**Comment by akshay-nm** [comment]
I am having the same issue? What is "correct" checkerboard image?

**Comment by akshay-nm** [comment]
The issue was not the images. We have to input the number of internal boxes in the checkerboard. I was passing the values including the outer boxes as well. This was based on the board generated by https://calib.io/pages/camera-calibration-pattern-generator,  if the generated pdf states say 6x7 then you have to input 5x6.
