### ISSUE TITLE
Pose Estimation Error

### ISSUE THREAD

**Issue by elimorley** [GSNCodes/ArUCo-Markers-Pose-Estimation-Generation-Python#4]
First: Thank you for the great write up. I am having one issue however. 

my command:
python pose_estimation.py --K_Matrix /home/hybsys/Desktop/ArUCo-Markers-Pose-Estimation-Generation-Python-main/calibration_matrix.npy --D_Coeff /home/hybsys/Desktop/ArUCo-Markers-Pose-Estimation-Generation-Python-main/distortion_coefficients.npy --type DICT_5X5_100

my error:
Traceback (most recent call last):
  File "/home/hybsys/Desktop/ArUCo-Markers-Pose-Estimation-Generation-Python-main/pose_estimation.py", line 78, in <module>
    output = pose_esitmation(frame, aruco_dict_type, k, d)
  File "/home/hybsys/Desktop/ArUCo-Markers-Pose-Estimation-Generation-Python-main/pose_estimation.py", line 31, in pose_esitmation
    corners, ids, rejected_img_points = cv2.aruco.detectMarkers(gray, cv2.aruco_dict,parameters=parameters,
cv2.error: OpenCV(4.6.0) :-1: error: (-5:Bad argument) in function 'detectMarkers'
> Overload resolution failed:
>  - 'cameraMatrix' is an invalid keyword argument for detectMarkers()
>  - 'cameraMatrix' is an invalid keyword argument for detectMarkers()

Any thoughts would be greatly appreciated, thank you.

**Comment by GSNCodes** [comment]
Hey @elimorley ,

Glad to know that you find it useful. The issue you're facing is due the OpenCV version (4.6) you're using. The latest version has removed the camera and distortion parameters. Try using any of these versions: 4.3 - 4.5

I'll update the note in the README file for future reference.

**Comment by elimorley** [comment]
Thank you!
