### ISSUE TITLE
Accuracy improvements using solvepnp?

### ISSUE THREAD

**Issue by akshay-nm** [GSNCodes/ArUCo-Markers-Pose-Estimation-Generation-Python#5]

**Comment by GSNCodes** [comment]
SolvePnP is done in the background. But as always, accuracy can be improved further by tweaking the parameters. Nice suggestion.
Reference: https://docs.opencv.org/4.x/d9/d0c/group__calib3d.html#ga687a1ab946686f0d85ae0363b5af1d7b
