### ISSUE TITLE
Calibration not working for fisheye camera

### ISSUE THREAD

**Issue by baj31415** [GSNCodes/ArUCo-Markers-Pose-Estimation-Generation-Python#7]
Hi, I was trying to use this repository for a project. I'm using a fisheye camera and have collected about 28 images in a folder called calib. For some reason running the calibration file does not work for me.
I get the following error, can someone help to identify what this means?

<pre>Traceback (most recent call last):
  File &quot;calibration.py&quot;, line 102, in &lt;module&gt;
    ret, mtx, dist, rvecs, tvecs = calibrate(
  File &quot;calibration.py&quot;, line 51, in calibrate
    ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(
cv2.error: OpenCV(4.2.0) ../modules/calib3d/src/calibration.cpp:3681: error: (-215:Assertion failed) nimages &gt; 0 in function &apos;calibrateCameraRO&apos;</pre>

**Comment by GSNCodes** [comment]
Hello,
This is a late response, hope you have resolved your errors already. Just in case, here is my thought on this.
I guess there is some issue with the paths you use for reading in the images. Refer this SO thread: https://stackoverflow.com/questions/23819042/error-215-nimages-0-in-function-calibratecamera-using-python-and-opencv
