### ISSUE TITLE
 Algorithm

### ISSUE THREAD

**Issue by Olya907** [GSNCodes/ArUCo-Markers-Pose-Estimation-Generation-Python#8]
Hello! I would like to clarify which algorithm you used (formulas, description of the algorithm), what error does it give for coordinate values?

**Comment by GSNCodes** [comment]
Check the references section. 
Specifically, 
1) https://docs.opencv.org/4.x/da/d13/tutorial_aruco_calibration.html
2) https://cs-courses.mines.edu/csci507/schedule/24/ArUco.pdf

These are links obtained from the references quoted.
